// <auto-generated />
namespace Quanlytrungtamngoaingu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changesodt_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changesodt_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201907230706431_changesodt_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
